Repository aicoe-aiops/github-labeler, pull requests merged in 2021-08, with the labels that each got.

#26 Precommit
  reports/existing_research.md
  src/data/make_dataset.py
Labels: approved, size/M

#5 adding fastText expirement notebook
  models/fastText_expirements.ipynb
Labels: approved, size/XXL

#27 update maintainers
  .thoth.yaml
Labels: size/XS, approved

#3 data extraction added
  src/data/issue_extraction.ipynb
Labels: size/XL, approved

#31 fixed some bugs for functionality in elyra pipeline
  .aicoe-ci.yaml
  models/fastText_expirements.ipynb
Labels: approved, size/XXL

#34 Image
  .aicoe-ci.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/XXL
