Repository aicoe-aiops/github-labeler, pull requests merged in 2021-09, with the labels that each got.

#45 Functionality for SVM's implemented
  Pipfile
  Pipfile.lock
  app.py
  models/fastText_expirements.ipynb
Labels: approved, size/XXL

#53 pretraining notebook added
  src/data/pretrain_w2v.ipynb
Labels: size/XL, approved

#56 Minor updates in README.md
  README.md
Labels: approved, size/M

#54 Adding markdown on notebooks
  models/fastText_expirements.ipynb
  notebooks/fastText_viz.ipynb
  src/data/issue_extraction.ipynb
Labels: lgtm, approved, size/L

#60 Add aakankshaduggal to owners
  OWNERS
Labels: size/XS, approved

#62 fixed existing_research.md
  reports/existing_methods_research.md
  reports/existing_research.md
Labels: size/XS, lgtm, approved

#63 downloaded stopwords
  src/data/preprocess.py
Labels: size/XS, lgtm, approved

#64 Re-organizing and Updating
  app.py
  models/model_classes.py
  models/train_models.ipynb
  notebooks/preprocess.ipynb
  src/data/preprocess.py
Labels: approved, size/XXL

#65 mkdir is in os not os.path
  app.py
Labels: size/XS, approved

#69 changed port
  app.py
Labels: size/XS, approved

#70 readiness probe was failing
  app.py
Labels: size/S

#71 should not have used text editor to update code
  app.py
Labels: approved, size/S

#72 nltk download punkt :/
  src/data/preprocess.py
Labels: size/XS

#74 fixed error output
  src/data/issue_extraction.ipynb
Labels: approved, size/M
